name: "Nightly Run Integration Tests"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # This runs the workflow every day at 9:00 AM UTC

permissions:
  contents: read

jobs:

  nightly-run:
    runs-on: runs-on,runner=2cpu-linux-x64,run-id=${{ github.run_id }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install Dependencies and Run Linter
        uses: ./.github/actions/dep_install_and_lint
        with:
          working-directory: .

      - name: Run Integration Tests
        run: cargo test --manifest-path integration-tests/Cargo.toml
        working-directory: .
